# -*- coding: utf-8 -*-
"""Regressão Linear - baseada em Solução Projeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_CdWpAzJV5MywomHW0Z7s-YWJiTaLhsE
https://colab.research.google.com/drive/1_CdWpAzJV5MywomHW0Z7s-YWJiTaLhsE?usp=sharing

# Regressão Linear - Projeto

Você obteve algum contrato de trabalho com uma empresa de comércio eletrônico com sede na cidade de Ulan Bator que vende roupas online, 
mas também tem sessões de consultoria em estilo e vestuário na loja.

Os clientes entram na loja, têm sessões / reuniões com um estilista pessoal, 
então podem ir para casa e encomendarem em um aplicativo móvel ou site para a roupa que desejam.

A empresa está tentando decidir se deve concentrar seus esforços em sua experiência em aplicativos móveis ou em seu site.

Eles contrataram você no contrato para ajudá-los a descobrir isso!
"""

#%% bibliotecas 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""## Obter dados

Trabalharemos com o arquivo csv do Ecommerce Customers da empresa.

Possui informações do cliente, como Email, Endereço e sua cor Avatar. Em seguida, ele também possui colunas de valores numéricos:.

* Avg. Session Length: Tempo médio das sessões de consultoria de estilo na loja.
* Time on App: tempo médio gasto no app em minutos.
* Time on Website: tempo médio gasto no site em minutos.
* Length of Membership: Há quantos anos o cliente é membro.

"""
#%% SE GOOGLE COLAB
from google.colab import files

# Subir o arquivo CSV
uploaded = files.upload()   # sobe o arquivo de modo interativo

# Verificar se o arquivo foi subido com sucesso
if uploaded:
  print("Arquivo subido com sucesso!")
else:
  print("Erro ao subir o arquivo.")

#%% SE ARQUIVO LOCAL 

customers = pd.read_csv("Ecommerce Customers")
customers.head()
customers.describe()
customers.info()

##%% Análise de dados exploratória

sns.set_palette("Grays_r")  # cinzas reverso
sns.set_style('whitegrid')
sns.pairplot(customers)

"""** Baseado neste plot o que parece ser a característica mais correlacionada 
com o valor anual gasto (Yearly Amount Spent)? **"""

#%% Tempo anual gasto

sns.lmplot(x='Length of Membership', y='Yearly Amount Spent', data=customers)

#%% Treinando e testando os dados
"""
Agora que exploramos um pouco os dados, vamos avançar e dividir os dados em conjuntos 
de treinamento e teste.
Defina uma variável X igual a todas as características numéricas dos clientes e 
uma variável y igual à coluna Valor anual gasto (Yearly Amount Spent). **
"""

y = customers['Yearly Amount Spent']

X = customers[['Avg. Session Length', 'Time on App','Time on Website', 'Length of Membership']]

#%% DADOS DE TREINAMENTO E TESTE
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

#%% Treinando o modelo
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

#%% TREINAR O MODELO
lm.fit(X_train,y_train)
print('Coeficientes: \n', lm.coef_)

#%% Previsão de dados de teste
prev = lm.predict( X_test)

#%% GRÁFICO DOS DADOS X Y
plt.scatter(y_test, prev)
plt.xlabel('Y Test')
plt.ylabel('Y previsto')

#%% Avaliando o Modelo
from sklearn import metrics
print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

#%% Resíduos
sns.distplot((y_test-predictions),bins=50);

#%% Conclusão
"""
Ainda desejamos descobrir a resposta à pergunta original, 
concentramos-nos no desenvolvimento de aplicativos móveis ou de sites? 
Ou talvez isso realmente não importe, e o tempo como membro é o que realmente importa? 
Vamos ver se podemos interpretar os coeficientes para ter uma idéia.
"""

coefs = pd.DataFrame(lm.coef_, X.columns)
coefs.columns = ['Coeficiente']
print(coefs)

"""
Interpretando os coeficientes:

**Mantendo todos as outras variáveis constantes**, 
um aumento de 1 unidade na média de tempo de uso 
está associado a um aumento de 25,98 dólares totais gastos.

**Mantendo todos as outras variáveis constantes**, 
um aumento de 1 unidade no tempo gasto no App 
está associado a um aumento de 38,59 dólares totais gastos.

**Mantendo todos as outras variáveis constantes**, 
um aumento de 1 unidade no tempo no site 
está associado a um aumento de 0,19 dólares em dólares.

**Mantendo todos as outras variáveis constantes**, 
um aumento de 1 unidade no tempo de Associação 
está associado a um aumento de 61,27 dólares em dólares.

** Você acha que a empresa deve se concentrar mais em seu aplicativo móvel ou 
em seu site? **

Primeiramente, a empresa provavelmente deveria arranjar outras formas de fidelizar 
seu cliente, já que essa é a variável que mais influencia os gastos dos seus usuários. 
Entre site e aplicativo, investiriamos no aplicativo, dado que o mesmo apresenta 
um coeficiente significativamente maior do que o site.
"""


# %%
